sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:18.04

script:
  - docker run --rm -v $PWD:/katran ubuntu:18.04 /bin/sh -c "
    apt-get update && apt-get install -y git sudo wget;
    cd /katran && ./build_katran.sh"
